name: Build FlashBox IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar XcodeGen
        run: brew install xcodegen

      - name: Preparar Ruffle
        run: |
          mkdir -p FlashBox/Resources/Ruffle
          curl -L "https://github.com/ruffle-rs/ruffle/releases/download/nightly-2026-10-05/ruffle-nightly-2026_10_05-web-selfhosted.zip" -o ruffle.zip
          unzip -q ruffle.zip -d FlashBox/Resources/Ruffle
          rm ruffle.zip

      - name: Generar proyecto Xcode
        run: xcodegen generate

      - name: Compilar FlashBox
        run: |
          xcodebuild \
            -project FlashBox.xcodeproj \
            -scheme FlashBox \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Crear IPA
        run: |
          mkdir -p Payload
          cp -R build/Release-iphoneos/FlashBox.app Payload/
          zip -r FlashBox.ipa Payload

      - name: Guardar IPA
        uses: actions/upload-artifact@v4
        with:
          name: FlashBox-IPA
          path: FlashBox.ipa

      - name: Guardar IPA
        uses: actions/upload-artifact@v4
        with:
          name: FlashBox-IPA
          path: FlashBox.ipa
